# Generated by Django 5.2.3 on 2025-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="preferred_professor",
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(default="남", max_length=10, verbose_name="성별"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="grade",
            field=models.CharField(default="1", max_length=10, verbose_name="학년"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="홍길동", max_length=30, verbose_name="이름"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(
                default="20250001", max_length=20, verbose_name="학번"
            ),
        ),
    ]
